### ISSUE TITLE
The demo is empty, did I miss something?

### ISSUE THREAD

**Issue by imgen** [MicrosecLtdUk/VirtualizingObservableCollectionDemo#1]
The demo is completely empty page with "Welcome to Xamarin Forms" label in the middle, did I miss something or this project is not started yet?

**Comment by ghost** [comment]
That's strange - I'll check what's going on!

**Comment by ghost** [comment]
You're right - my apologies, something's gone wrong with the git submission. I'll take a look and try to fix it.

**Comment by ghost** [comment]
I've pushed the full project now - somehow Xamarin Studio hadn't committed/pushed properly.

I've downloaded a clone and built/run it and it runs OK now (tested on Droid, my iOS simulator has just decided to stop working).
